import React, { useState } from 'react';
import axios from 'axios';

const ImageGenerator = () => {
    const [description, setDescription] = useState('');
    const [image, setImage] = useState('');
    const [loading, setLoading] = useState(false);

    const handleGenerate = async () => {
        setLoading(true);
        let images = [];
        try {
            for (let i = 0; i < 4; i++) {
                const response = await axios.post(
                    'http://127.0.0.1:5000/generate-image',
                    { description: description },
                    {
                        headers: {
                            'Content-Type': 'application/json',
                        },
                    }
                );
                images.push(response.data.image_url);
            }
            // Display the last generated image or combine results as needed
            setImage(images[images.length - 1]);
        } catch (error) {
            console.error('Error generating image:', error);
        } finally {
            setLoading(false);
        }
    };
    

    return (
        <div style={{ width: '100%', maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
            <h2>Image Generator</h2>
            <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter image description"
                rows="4"
            />
            <br />
            <button onClick={handleGenerate} disabled={loading}>
                {loading ? 'Generating...' : 'Generate Image'}
            </button>
            {image && (
                
                <div style={{ marginTop: '5px' }}>
                    <div style={{ fontSize: '0.9rem', color: '#555' }}>
                        Image generated by our T2FGAN
                    </div>
                    <img src={image} alt="Generated" style={{ width: '250px', height: 'auto' }} />
                    <br />
                    <a href={image} download>
                        <button>Download Image</button>
                    </a>
                </div>
            )}
            <footer style={{ marginTop: '40px', color: '#aaa' }}>
                Powered by T2FGAN | <a href="#" style={{ color: '#61dafb' }}>Learn more</a>
            </footer>
        </div>
    );
};

export default ImageGenerator;
