import React, { useState } from 'react';
import axios from 'axios';

const ImageGenerator = () => {
    const [description, setDescription] = useState('');
    const [image, setImage] = useState('');
    const [loading, setLoading] = useState(false);

    const handleGenerate = async () => {
        setLoading(true);
        try {
            const response = await axios.post('http://localhost:5000/generate-image', {
                description: description,
            });
            // Assuming the response contains the URL of the generated image
            setImage(response.data.image_url); 
        } catch (error) {
            console.error('Error generating image:', error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div>
            <h1>Image Generator</h1>
            <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter image description"
                rows="4"
                cols="50"
            />
            <br />
            <button onClick={handleGenerate} disabled={loading}>
                {loading ? 'Generating...' : 'Generate Image'}
            </button>
            <div>Image generated by our T2FGAN</div>
            <div style={{ marginTop: '20px' }}>
                {image && <img src={image} alt="Generated" style={{ maxWidth: '100%' }} />}
            </div>
        </div>
    );
};

export default ImageGenerator;
